#!/bin/sh
# Xcode Cloud post-clone hook.
#
# This repo is source-only: Stripie.xcodeproj is generated by XcodeGen from
# project.yml and is gitignored. Xcode Cloud clones the repo and then expects a
# .xcodeproj/.xcworkspace to exist, so we generate it here before the build
# resolves dependencies.
#
# Runs automatically after `git clone` on the Xcode Cloud runner.
set -euo pipefail

echo "==> Installing XcodeGen via Homebrew"
# Homebrew is preinstalled on Xcode Cloud runners.
brew install xcodegen

echo "==> Generating Stripie.xcodeproj from project.yml"
# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the cloned repo root.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(dirname "$0")/..}"
xcodegen generate

echo "==> Project generated:"
ls -d Stripie.xcodeproj
