#!/bin/sh
# Xcode Cloud post-clone hook.
#
# This repo is source-only: Stripie.xcodeproj is generated by XcodeGen from
# project.yml and is gitignored. Xcode Cloud clones the repo and then expects a
# .xcodeproj/.xcworkspace to exist, so we generate it here before the build
# resolves dependencies.
#
# Runs automatically after `git clone` on the Xcode Cloud runner.
set -euo pipefail

echo "==> Installing XcodeGen via Homebrew"
# Homebrew is preinstalled on Xcode Cloud runners.
brew install xcodegen

echo "==> Generating Stripie.xcodeproj from project.yml"
# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the cloned repo root.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(dirname "$0")/..}"
xcodegen generate

echo "==> Project generated:"
ls -d Stripie.xcodeproj

# Xcode Cloud runs with automatic SPM resolution disabled, so
# -resolvePackageDependencies refuses to run unless a Package.resolved
# already exists at this path. We commit one (see .gitignore) so xcodegen's
# freshly generated xcworkspace already has it before this runs — this call
# just fetches the pinned source archive into the SourcePackages cache.
echo "==> Resolving Swift Package dependencies"
xcodebuild -resolvePackageDependencies \
  -project Stripie.xcodeproj \
  -scheme Stripie

echo "==> Package.resolved:"
ls -l Stripie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
