#!/bin/sh
# Xcode Cloud post-clone hook.
#
# This repo is source-only: Stripie.xcodeproj is generated by XcodeGen from
# project.yml and is gitignored. Xcode Cloud clones the repo and then expects a
# .xcodeproj/.xcworkspace to exist, so we generate it here before the build
# resolves dependencies.
#
# Runs automatically after `git clone` on the Xcode Cloud runner.
set -euo pipefail

echo "==> Installing XcodeGen via Homebrew"
# Homebrew is preinstalled on Xcode Cloud runners.
brew install xcodegen

echo "==> Generating Stripie.xcodeproj from project.yml"
# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the cloned repo root.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(dirname "$0")/..}"
xcodegen generate

echo "==> Project generated:"
ls -d Stripie.xcodeproj

# Xcode Cloud runs with automatic SPM resolution disabled, so it requires a
# Package.resolved to already exist. Our .xcodeproj (and its Package.resolved)
# is generated, not committed, so resolve dependencies here to create it before
# the build phase runs.
echo "==> Resolving Swift Package dependencies"
# Xcode Cloud sets the IDEDisableAutomaticPackageResolution user default to
# enforce reproducible builds from a committed Package.resolved. We don't
# commit one (it's generated fresh from project.yml every run), so this
# default makes even our explicit -resolvePackageDependencies call refuse to
# run. Override it for this run so resolution can proceed from scratch.
defaults write com.apple.dt.Xcode IDEDisableAutomaticPackageResolution -bool NO
xcodebuild -resolvePackageDependencies \
  -project Stripie.xcodeproj \
  -scheme Stripie

echo "==> Package.resolved:"
ls -l Stripie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
